import { Form } from "react-bootstrap";

type Props = {
  title: string;
  setTitle: (value: string) => void;
  author: string;
  setAuthor: (value: string) => void;
  slug: string;
  onTitleBlur: () => void;
};
export default function BlogMetaSection(props: Props) {
  const { title, setTitle, author, setAuthor, onTitleBlur, slug } = props;
  return (
    <>
      <Form.Group>
        <Form.Label className="fw-semibold fs-6 mb-1">
          Title <span style={{ color: "red" }}>*</span>
        </Form.Label>
        <Form.Control
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          onBlur={onTitleBlur}
          placeholder="Enter blog's title"
        />
        <Form.Text className="text-muted">
          A clear and descriptive title helps with SEO.
        </Form.Text>
      </Form.Group>

      <Form.Group>
        <Form.Label className="fw-semibold fs-6 mb-1">
          Author <span style={{ color: "red" }}>*</span>
        </Form.Label>
        <Form.Control
          type="text"
          value={author}
          onChange={(e) => setAuthor(e.target.value)}
          placeholder="Enter blog's author"
        />
      </Form.Group>

      <Form.Group>
        <Form.Label className="fw-semibold fs-6 mb-1">
          Slug <span style={{ color: "red" }}>*</span>
        </Form.Label>
        <Form.Control
          type="text"
          value={slug}
          readOnly
          placeholder="slug is auto-generated"
        />
        <Form.Text muted>Slug is auto generated by your title</Form.Text>
      </Form.Group>
    </>
  );
}
