
spring.application.name=blogs_management
server.port=8081

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


app.jwt.secret=${APP_JWT_SECRET:blogs-management-local-secret-key-2026}
app.jwt.issuer=blogs-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# refresh cookie (local dev)
app.auth.refresh-cookie.name=refresh_token
app.auth.refresh-cookie.path=/
# local dev không co secure (http - not https)
app.auth.refresh-cookie.secure=false
app.auth.refresh-cookie.same-site=Lax

spring.profiles.active=local

app.storage.base-url=https://jrkitnrinrhvetvtrykv.supabase.co/storage/v1/object/public
app.supabase.url=https://jrkitnrinrhvetvtrykv.supabase.co
app.supabase.service-key=sb_publishable_QX_TO5ujBlUrn0Al7q_uxQ_El8xb_em
app.supabase.bucket=blog-images
