
spring.application.name=blogs_management
server.port=8081

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


app.jwt.secret=${APP_JWT_SECRET:blogs-management-local-secret-key-2026}
app.jwt.issuer=blogs-management

# refresh cookie (local dev)
app.auth.refresh-cookie.name=refresh_token
app.auth.refresh-cookie.path=/
# local dev không co secure (http - not https)
app.auth.refresh-cookie.secure=false
app.auth.refresh-cookie.same-site=Lax

spring.profiles.active=local
